namespace Gley.Localization
{
	public enum WordIDs
	{
		BackID = 7,
		ContinueID = 19,
		ControllableID = 14,
		Description_Floor3_ID = 30,
		Description_Floor4_5_ID = 31,
		Description_Floor6_ID = 32,
		EnterID = 13,
		ExitID = 2,
		FloorID = 10,
		IDLanguageEnglish = 12,
		IDLanguageRussian = 11,
		InventoryID = 16,
		LanguageID = 6,
		MasterVolumeID = 8,
		MouseSensitivityID = 15,
		NULLID = 0,
		ProfileID = 17,
		ReconnectID = 3,
		SettingID = 1,
		SoundID = 5,
		SoundVolumeID = 9,
		Title_Floor3_ID = 20,
		Title_Floor4_ID = 21,
		Title_Floor5_ID = 22,
		Title_Floor6_ID = 23,
		VideoID = 4,
		ViewPlayerID = 25,
		WantQuitID = 18,
		WorkInProgressID = 24,
		ChatID = 26,
	}
}