using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using Mirror;
using System.Text;
using System.IO;
using UnityEditor;
using BitterECS.Core;

[CreateAssetMenu(fileName = "NetworkObjectPrefabConfig", menuName = "Network/Network Object Prefab Config")]
public partial class NetworkObjectPrefabConfig : ScriptableObject
{
    private const string PathToPrefabIdClass = "Assets/!META/!Scripts/Utility/NetworkFeature/";
    [Serializable]
    public class NetworkPrefabMapping
    {
        [SerializeField] private string _prefabId;
        [SerializeField] private GameObject _prefab;
    
        public GameObject Prefab => _prefab;
        public string PrefabId => _prefabId;
        public NetworkIdentity NetworkIdentity { get; private set; }

        public void Validate()
        {
            if (_prefab == null)
            {
                LoggerUtility.Error("Prefab is null in mapping");
                return;
            }

            _prefabId = TextFormatterUtility.ConvertToUpperUnderscore(_prefab.name);

            NetworkIdentity = _prefab.GetComponent<NetworkIdentity>();
            if (NetworkIdentity == null)
            {
                LoggerUtility.Error($"Prefab {_prefab.name} doesn't have NetworkIdentity component");
            }
        }
    }

    public List<NetworkPrefabMapping> prefabMappings = new();

    public void RegisterAllPrefabs()
    {
        foreach (var mapping in prefabMappings)
        {
            if (mapping.Prefab != null && mapping.NetworkIdentity != null)
            {
                if (!NetworkClient.prefabs.ContainsValue(mapping.Prefab))
                {
                    NetworkClient.RegisterPrefab(mapping.Prefab);
                }
            }
        }
    }

    public GameObject GetPrefabById(string prefabId)
    {
        var mapping = prefabMappings.FirstOrDefault(m =>
            string.Equals(m.PrefabId, prefabId, StringComparison.OrdinalIgnoreCase));

        if (mapping != null)
        {
            return mapping.Prefab;
        }

        LoggerUtility.Error($"Prefab with ID {prefabId} not found in config");
        return null;
    }

    public bool TryGetPrefabById(string prefabId, out GameObject prefab)
    {
        var mapping = prefabMappings.FirstOrDefault(m =>
            string.Equals(m.PrefabId, prefabId, StringComparison.OrdinalIgnoreCase));

        prefab = mapping?.Prefab;
        return prefab != null;
    }

    public bool ContainsPrefab(string prefabId)
    {
        return prefabMappings.Any(m =>
            string.Equals(m.PrefabId, prefabId, StringComparison.OrdinalIgnoreCase));
    }

    public bool ContainsPrefab(GameObject prefab)
    {
        return prefabMappings.Any(m => m.Prefab == prefab);
    }

    public IReadOnlyList<NetworkPrefabMapping> GetAllMappings() => prefabMappings;

#if UNITY_EDITOR
    private void OnValidate()
    {
        var usedIds = new HashSet<string>();
        var hasDuplicates = false;
        var hasInvalidPrefabs = false;

        // Create a new list to store valid mappings
        var validMappings = new List<NetworkPrefabMapping>();

        foreach (var mapping in prefabMappings)
        {
            if (mapping.Prefab == null)
            {
                LoggerUtility.Error("Null prefab found in mappings - it will be removed");
                hasInvalidPrefabs = true;
                continue;
            }

            mapping.Validate();

            if (mapping.NetworkIdentity == null)
            {
                LoggerUtility.Error($"Prefab {mapping.Prefab.name} doesn't have NetworkIdentity - it will be removed from mappings");
                hasInvalidPrefabs = true;
                continue;
            }

            var id = mapping.PrefabId;
            if (usedIds.Contains(id))
            {
                LoggerUtility.Error($"Duplicate prefab ID: {id} for prefab {mapping.Prefab.name}");
                hasDuplicates = true;
                continue;
            }

            usedIds.Add(id);
            validMappings.Add(mapping);
        }

        if (hasInvalidPrefabs || hasDuplicates)
        {
            prefabMappings = validMappings;
            EditorUtility.SetDirty(this);
        }
    }

    public void GeneratePrefabIdClass()
    {
        if (prefabMappings == null || prefabMappings.Count == 0)
        {
            LoggerUtility.Warning("No prefab mappings to generate IDs");
            return;
        }

        var nameScript = "IDConstPrefabs";

        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED CLASS - DO NOT MODIFY");
        sb.AppendLine("// This file is automatically generated by NetworkObjectPrefabConfig");
        sb.AppendLine("// Last generated: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
        sb.AppendLine();
        sb.AppendLine($"public static class {nameScript}");
        sb.AppendLine("{");

        foreach (var mapping in prefabMappings)
        {
            if (mapping.Prefab != null && !string.IsNullOrEmpty(mapping.PrefabId))
            {
                string fieldName = mapping.PrefabId;
                sb.AppendLine($"    public const string {fieldName} = \"{mapping.PrefabId}\";");
            }
        }

        sb.AppendLine("}");

        if (!Directory.Exists(PathToPrefabIdClass))
        {
            Directory.CreateDirectory(PathToPrefabIdClass);
        }

        var filePath = Path.Combine(PathToPrefabIdClass, $"{nameScript}.cs");
        File.WriteAllText(filePath, sb.ToString());
        AssetDatabase.Refresh();

        LoggerUtility.Info($"Prefab ID class generated at: {filePath}");
    }

#endif
}
