//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/!META/Resources/Settings/Control/ControlsConfig.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlsConfig: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlsConfig()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlsConfig"",
    ""maps"": [
        {
            ""name"": ""Playable"",
            ""id"": ""49dc5821-c6f5-4495-8aa6-12a76235d210"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""fa1d5f92-4f96-4f29-b048-0ce6f45e68fd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""76b68679-166e-43ff-92fb-d15143b5eabc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""967fb07f-3fc3-4975-bb95-1f6bb3ba7d0f"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""a43eddb7-d4b9-4595-bd77-1a4d5dc0268c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""49cae814-84d4-413f-9565-453b777b2019"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""2ca5ef82-4b29-49e3-bc02-ddab288b9ac6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""87008f17-60b8-4b7b-9f5c-f643d68019b9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""8a153c12-45eb-4261-8a5a-625234408dbb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""49a0ddfd-1919-49c4-b2c9-bbcffea844f0"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ea45198-430b-47bd-be4b-fb1fe32dd536"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Playable
        m_Playable = asset.FindActionMap("Playable", throwIfNotFound: true);
        m_Playable_Move = m_Playable.FindAction("Move", throwIfNotFound: true);
        m_Playable_Look = m_Playable.FindAction("Look", throwIfNotFound: true);
    }

    ~@ControlsConfig()
    {
        UnityEngine.Debug.Assert(!m_Playable.enabled, "This will cause a leak and performance issues, ControlsConfig.Playable.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Playable
    private readonly InputActionMap m_Playable;
    private List<IPlayableActions> m_PlayableActionsCallbackInterfaces = new List<IPlayableActions>();
    private readonly InputAction m_Playable_Move;
    private readonly InputAction m_Playable_Look;
    public struct PlayableActions
    {
        private @ControlsConfig m_Wrapper;
        public PlayableActions(@ControlsConfig wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Playable_Move;
        public InputAction @Look => m_Wrapper.m_Playable_Look;
        public InputActionMap Get() { return m_Wrapper.m_Playable; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayableActions set) { return set.Get(); }
        public void AddCallbacks(IPlayableActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayableActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayableActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
        }

        private void UnregisterCallbacks(IPlayableActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
        }

        public void RemoveCallbacks(IPlayableActions instance)
        {
            if (m_Wrapper.m_PlayableActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayableActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayableActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayableActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayableActions @Playable => new PlayableActions(this);
    public interface IPlayableActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
    }
}
