// AUTO-GENERATED CLASS - DO NOT MODIFY
// This file is automatically generated by NetworkObjectPrefabConfig
// Last generated: 2025-08-09 19:26:11

public static class IDConstPrefabs
{
    public const string PLAYER_TEST = "PLAYER_TEST";
}
